on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Build
        run: yarn run build
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
